name: nir
num_classes: 10
sup_size: 128
unsup_size: 128
eval_size: 2048
lr: 0.01

axis:
dim_aug: random # dim_aug can be all, random, same or different
alpha: 0
beta: 0
dropout: True
bn: True
w_augs:
  - name: jitter
    alpha: 0
    beta: 0
s_augs:
  - name: scaling
    alpha: 0
    beta: 0
  - name: magwarp
    alpha: 0
    beta: 0