name: cls10ww
num_classes: 10
axis: 0
sup_size: 1024
unsup_size: 1024
eval_size: 1024
lr: 0.01
alpha: 0
beta: 0
w_augs:
  - name: magwarp
    alpha: 0
    beta: 0
s_augs:
  - name: scaling
    alpha: 0
    beta: 0
  - name: magwarp
    alpha: 0
    beta: 0