name: cls50
num_classes: 50
axis: 0
sup_size: 1024
unsup_size: 1024
eval_size: 1024
lr: 0.01
w_augs:
  - name: jitter
    alpha: 0.674
    beta: 0.259
  - name: magwarp
    alpha: 0.02
    beta: 0
  - name: scaling
    alpha: 0.524
    beta: 0.092
s_augs:
  - name: jitter
    alpha: 0.674
    beta: 0.259
  - name: magwarp
    alpha: 0.02
    beta: 0
  - name: scaling
    alpha: 0.524
    beta: 0.092